//! Native request blocking via `WKContentRuleList`.
//!
//! Two rule lists, compiled separately because they have different
//! lifetimes and different authority:
//!
//! - **Ads.** [`ADS_JSON`] is Null's own list, generated from
//!   `scripts/blocklist/null-list.txt` and compiled into the binary.
//!   It is off unless the user turns it on. Updating it is a commit,
//!   never a fetch — nothing here reaches the network, at launch or
//!   ever (invariant 2).
//! - **User origins.** Whatever the user shielded in the Network
//!   Inspector, read from SQLite and recompiled on every change.
//!
//! A rule list is enforced by WebKit before a request is issued, so a
//! blocked request never leaves the machine. That is why it does not
//! appear in the Network Inspector: the inspector shows outbound
//! connections, and this is the absence of one.
//!
//! The ads list deliberately does not carry the `document` resource
//! type. Main-frame navigations stay on the `on_navigation` path in
//! [`crate::network`], where they are recorded and visible. User
//! origins do carry every resource type, `document` included — that
//! closes the popup route, which `on_navigation` alone never covered.

use serde_json::{json, Value};

/// Null's own ad and tracker rules, generated by
/// `scripts/blocklist/generate.mjs`. Public so the constant is part of
/// the crate's surface on every platform, not just the one that
/// compiles it into WebKit.
pub const ADS_JSON: &str = include_str!("ads.json");

/// Settings key holding `"true"` / `"false"`. Absent means off.
pub const SETTING_KEY: &str = "ad_blocking";

/// One user-blocked origin as a WebKit content-blocker rule, or `None`
/// if the string is not an http(s) origin.
///
/// No `resource-type` key: WebKit reads that as every type, `document`
/// included. Naming the types explicitly would be more legible and
/// less correct — the vocabulary grows between WebKit releases, and a
/// single unrecognised string makes the whole list fail to compile.
fn origin_rule(origin: &str) -> Option<Value> {
    let url = tauri::Url::parse(origin).ok()?;
    if !matches!(url.scheme(), "http" | "https") {
        return None;
    }
    let host = url.host_str()?;
    if host.is_empty() {
        return None;
    }
    let tail = match url.port() {
        Some(port) => format!(":{port}/"),
        // No port in the origin means any port, and a canonical URL
        // always has a path, so one of the two characters is always
        // there to match.
        None => "[:/]".to_string(),
    };
    // The subdomain wildcard is what makes shielding an ad host stick
    // (they rotate subdomains), but it only applies to multi-label
    // hosts: on a single label it would turn "block https://com" —
    // one shield click on a garbage request a page baited into the
    // Inspector — into a rule matching every .com site's subresources.
    let prefix = if host.contains('.') {
        "([a-z0-9_-]+\\.)*"
    } else {
        ""
    };
    let filter = format!("^https?://{}{}{}", prefix, escape_regex(host), tail);
    Some(json!({
        "trigger": { "url-filter": filter },
        "action": { "type": "block" },
    }))
}

/// The user's blocked origins as one content-blocker document, or
/// `None` when none of them survived parsing — an empty rule array is
/// not a valid list and WebKit refuses it.
pub fn user_rules_json(origins: &[String]) -> Option<String> {
    let rules: Vec<Value> = origins.iter().filter_map(|o| origin_rule(o)).collect();
    if rules.is_empty() {
        return None;
    }
    serde_json::to_string(&Value::Array(rules)).ok()
}

/// Everything with meaning inside a `url-filter`. A host from a parsed
/// URL is normally just letters, digits, dots and hyphens, but an IPv6
/// literal arrives in brackets, so this covers the whole set rather
/// than the expected one.
const REGEX_META: &str = ".*+?^${}()|[]\\/";

/// Literal text for WebKit's `url-filter`, which is a regex.
fn escape_regex(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        if REGEX_META.contains(c) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(target_os = "macos")]
mod mac {
    use std::cell::RefCell;
    use std::sync::atomic::{AtomicBool, Ordering};

    use block2::RcBlock;
    use objc2::rc::Retained;
    use objc2_foundation::{MainThreadMarker, NSArray, NSError, NSString};
    use objc2_web_kit::{WKContentRuleList, WKContentRuleListStore, WKUserContentController};
    use tauri::{AppHandle, Manager};

    use crate::storage::Storage;

    /// Identifier the user list is always stored under. Its content
    /// changes whenever the user shields an origin, so it is
    /// overwritten in place rather than versioned.
    const USER_IDENTIFIER: &str = "null-user";

    /// Prefix of every identifier this app has ever written for the
    /// bundled list. Used to sweep the ones a previous build left.
    const ADS_PREFIX: &str = "null-ads-";

    /// Off until the user says otherwise. Blocking changes what pages
    /// receive, and a browser that quietly rewrites pages on first
    /// launch is making a decision that is not its to make.
    static ADS_ENABLED: AtomicBool = AtomicBool::new(false);

    /// Generation counter for the user list. Commands run on tauri's
    /// async runtime, so two rapid shield toggles can reach the store
    /// in either order — and the compile that lands *last* would
    /// silently become authoritative. Each recompile takes a ticket at
    /// the moment it reads SQLite; a completion only installs its list
    /// if its ticket is still the newest, so a stale compile can never
    /// overwrite a fresher one.
    static USER_GEN: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

    /// `Retained` is not `Send`, and `WKContentRuleList` is main-thread
    /// only, so the compiled lists live in main-thread-local storage.
    /// Every function below either starts on the main thread or hops
    /// there first, and reaches this only from inside that hop.
    #[derive(Default)]
    struct CompiledLists {
        ads: Option<Retained<WKContentRuleList>>,
        user: Option<Retained<WKContentRuleList>>,
    }

    thread_local! {
        static COMPILED: RefCell<CompiledLists> = RefCell::new(CompiledLists::default());
    }

    /// Store identifier for the current bundled list.
    ///
    /// WebKit persists compiled lists on disk, so this is a lookup hit
    /// on every launch after the first — compilation happens once per
    /// version of the list. The hash is only required to differ when
    /// the bytes differ; `DefaultHasher` changing between Rust
    /// releases costs one extra compile, not correctness.
    fn ads_identifier() -> String {
        use std::hash::{Hash, Hasher};
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        super::ADS_JSON.hash(&mut hasher);
        format!("{ADS_PREFIX}{:016x}", hasher.finish())
    }

    /// Read the persisted state and get both lists ready.
    ///
    /// Called from `setup`, which is already on the main thread. The
    /// completion handlers land on the main queue once the run loop
    /// pumps, so nothing here waits: tabs that open before a list is
    /// ready get it applied by [`apply_to_all`] when it arrives.
    pub fn init(app: &AppHandle) {
        let (enabled, origins) = match app.try_state::<Storage>() {
            Some(storage) => (
                storage
                    .get_setting(super::SETTING_KEY)
                    .ok()
                    .flatten()
                    .map(|v| v == "true")
                    .unwrap_or(false),
                storage
                    .list_blocked_origins()
                    .map(|rows| rows.into_iter().map(|r| r.origin).collect::<Vec<_>>())
                    .unwrap_or_default(),
            ),
            None => (false, Vec::new()),
        };
        ADS_ENABLED.store(enabled, Ordering::Relaxed);
        compile_all(app, super::user_rules_json(&origins));
    }

    fn compile_all(app: &AppHandle, user_json: Option<String>) {
        let Some(mtm) = MainThreadMarker::new() else {
            return;
        };
        let Some(store) = (unsafe { WKContentRuleListStore::defaultStore(mtm) }) else {
            eprintln!("null-blocklist: no default WKContentRuleListStore");
            return;
        };
        sweep_stale_ads(&store);
        // Nothing is compiled for a feature the user has not switched
        // on. Turning it on later takes the same path from
        // `set_ads_enabled`.
        if ADS_ENABLED.load(Ordering::Relaxed) {
            compile_ads(app, &store);
        }
        match user_json {
            Some(json) => {
                let generation = USER_GEN.fetch_add(1, Ordering::SeqCst) + 1;
                compile_user(app, &store, &json, generation);
            }
            None => {
                COMPILED.with(|c| c.borrow_mut().user = None);
                apply_to_all(app);
            }
        }
    }

    /// Look the bundled list up first; compile only on a miss.
    fn compile_ads(app: &AppHandle, store: &Retained<WKContentRuleListStore>) {
        let identifier = ads_identifier();
        let lookup_app = app.clone();
        let lookup_store = store.clone();
        let lookup_id = identifier.clone();
        let handler = RcBlock::new(move |list: *mut WKContentRuleList, _err: *mut NSError| {
            if let Some(found) = unsafe { Retained::retain(list) } {
                COMPILED.with(|c| c.borrow_mut().ads = Some(found));
                apply_to_all(&lookup_app);
                return;
            }
            compile_ads_fresh(&lookup_app, &lookup_store, &lookup_id);
        });
        unsafe {
            store.lookUpContentRuleListForIdentifier_completionHandler(
                Some(&NSString::from_str(&identifier)),
                Some(&handler),
            );
        }
    }

    fn compile_ads_fresh(
        app: &AppHandle,
        store: &Retained<WKContentRuleListStore>,
        identifier: &str,
    ) {
        let done_app = app.clone();
        let handler = RcBlock::new(move |list: *mut WKContentRuleList, err: *mut NSError| {
            match unsafe { Retained::retain(list) } {
                Some(compiled) => {
                    COMPILED.with(|c| c.borrow_mut().ads = Some(compiled));
                    apply_to_all(&done_app);
                }
                // Fail open: browsing without the list beats not
                // browsing. The slot stays empty and the next launch
                // tries again.
                None => eprintln!(
                    "null-blocklist: ads list failed to compile: {}",
                    describe(err)
                ),
            }
        });
        unsafe {
            store.compileContentRuleListForIdentifier_encodedContentRuleList_completionHandler(
                Some(&NSString::from_str(identifier)),
                Some(&NSString::from_str(super::ADS_JSON)),
                Some(&handler),
            );
        }
    }

    fn compile_user(
        app: &AppHandle,
        store: &Retained<WKContentRuleListStore>,
        json: &str,
        generation: u64,
    ) {
        let done_app = app.clone();
        let handler = RcBlock::new(move |list: *mut WKContentRuleList, err: *mut NSError| {
            if USER_GEN.load(Ordering::SeqCst) != generation {
                // A newer recompile was issued while this one was in
                // flight; its result is the authoritative one.
                return;
            }
            match unsafe { Retained::retain(list) } {
                Some(compiled) => {
                    COMPILED.with(|c| c.borrow_mut().user = Some(compiled));
                    apply_to_all(&done_app);
                }
                None => eprintln!(
                    "null-blocklist: user list failed to compile: {}",
                    describe(err)
                ),
            }
        });
        unsafe {
            store.compileContentRuleListForIdentifier_encodedContentRuleList_completionHandler(
                Some(&NSString::from_str(USER_IDENTIFIER)),
                Some(&NSString::from_str(json)),
                Some(&handler),
            );
        }
    }

    /// Drop compiled lists a previous build wrote. They are keyed by
    /// content hash, so an edit to `null-list.txt` orphans the old one
    /// in WebKit's store where nothing would ever collect it.
    fn sweep_stale_ads(store: &Retained<WKContentRuleListStore>) {
        let keep = ads_identifier();
        let sweep_store = store.clone();
        let handler = RcBlock::new(move |ids: *mut NSArray<NSString>| {
            let Some(ids) = (unsafe { Retained::retain(ids) }) else {
                return;
            };
            for id in ids.iter() {
                let id = id.to_string();
                if !id.starts_with(ADS_PREFIX) || id == keep {
                    continue;
                }
                unsafe {
                    sweep_store.removeContentRuleListForIdentifier_completionHandler(
                        Some(&NSString::from_str(&id)),
                        None,
                    );
                }
            }
        });
        unsafe { store.getAvailableContentRuleListIdentifiers(Some(&handler)) };
    }

    fn describe(err: *mut NSError) -> String {
        match unsafe { Retained::retain(err) } {
            Some(err) => err.localizedDescription().to_string(),
            None => "unknown error".to_string(),
        }
    }

    /// Hand the current lists to one tab or popup webview.
    ///
    /// `removeAllContentRuleLists` first, so this is idempotent and a
    /// toggle never leaves a stale list attached. The controller wry
    /// hands back is the webview's own `WKUserContentController`.
    pub fn attach(webview: &tauri::Webview) {
        let _ = webview.with_webview(|pw| unsafe {
            apply_to_controller(&*(pw.controller() as *const WKUserContentController));
        });
    }

    /// Popup windows are their own `WebviewWindow`, not children of the
    /// main window, so they are not in `app.webviews()` at the moment
    /// they are built.
    pub fn attach_window(window: &tauri::WebviewWindow) {
        let _ = window.with_webview(|pw| unsafe {
            apply_to_controller(&*(pw.controller() as *const WKUserContentController));
        });
    }

    unsafe fn apply_to_controller(controller: &WKUserContentController) {
        controller.removeAllContentRuleLists();
        COMPILED.with(|c| {
            let lists = c.borrow();
            if ADS_ENABLED.load(Ordering::Relaxed) {
                if let Some(ads) = &lists.ads {
                    controller.addContentRuleList(ads);
                }
            }
            if let Some(user) = &lists.user {
                controller.addContentRuleList(user);
            }
        });
    }

    fn apply_to_all(app: &AppHandle) {
        for (label, webview) in app.webviews() {
            if label.starts_with("tab-") || label.starts_with("popup-") {
                attach(&webview);
            }
        }
    }

    /// The user shielded or unshielded an origin: rebuild that list.
    ///
    /// Takes effect on the next request, which for an already-rendered
    /// page means the next navigation. Nothing reloads on its own —
    /// throwing away a page the user is reading is not a privacy win.
    pub fn recompile_user_rules(app: &AppHandle) {
        // A failed read keeps the last compiled list. Treating it as
        // "zero origins" would silently drop native enforcement for
        // every shielded origin while SQLite still shows them blocked.
        let origins = match app.try_state::<Storage>().map(|s| s.list_blocked_origins()) {
            Some(Ok(rows)) => rows.into_iter().map(|r| r.origin).collect::<Vec<_>>(),
            _ => {
                eprintln!("null-blocklist: origin read failed; keeping the current user list");
                return;
            }
        };
        // The ticket is taken at read time: the highest generation is
        // the latest read, which saw every write before it.
        let generation = USER_GEN.fetch_add(1, Ordering::SeqCst) + 1;
        let json = super::user_rules_json(&origins);
        let handle = app.clone();
        let _ = app.run_on_main_thread(move || {
            let Some(mtm) = MainThreadMarker::new() else {
                return;
            };
            let Some(store) = (unsafe { WKContentRuleListStore::defaultStore(mtm) }) else {
                return;
            };
            if USER_GEN.load(Ordering::SeqCst) != generation {
                return;
            }
            match &json {
                Some(json) => compile_user(&handle, &store, json, generation),
                None => {
                    COMPILED.with(|c| c.borrow_mut().user = None);
                    apply_to_all(&handle);
                }
            }
        });
    }

    /// Settings toggled the bundled list. Same deal: next navigation.
    pub fn set_ads_enabled(app: &AppHandle, enabled: bool) {
        ADS_ENABLED.store(enabled, Ordering::Relaxed);
        let handle = app.clone();
        let _ = app.run_on_main_thread(move || {
            let ready = COMPILED.with(|c| c.borrow().ads.is_some());
            if enabled && !ready {
                let Some(mtm) = MainThreadMarker::new() else {
                    return;
                };
                let Some(store) = (unsafe { WKContentRuleListStore::defaultStore(mtm) }) else {
                    return;
                };
                compile_ads(&handle, &store);
                return;
            }
            apply_to_all(&handle);
        });
    }
}

#[cfg(target_os = "macos")]
pub use mac::{attach, attach_window, init, recompile_user_rules, set_ads_enabled};

// Everything below is the non-macOS shape of the same surface, mirroring
// the stubs in `webview::mod`. `WKContentRuleList` has no counterpart in
// WebKitGTK or WebView2, so on those platforms the pure layer above
// still parses and validates, and nothing is enforced.

#[cfg(not(target_os = "macos"))]
pub fn init(_app: &tauri::AppHandle) {}

#[cfg(not(target_os = "macos"))]
pub fn attach(_webview: &tauri::Webview) {}

#[cfg(not(target_os = "macos"))]
pub fn attach_window(_window: &tauri::WebviewWindow) {}

#[cfg(not(target_os = "macos"))]
pub fn recompile_user_rules(_app: &tauri::AppHandle) {}

#[cfg(not(target_os = "macos"))]
pub fn set_ads_enabled(_app: &tauri::AppHandle, _enabled: bool) {}

#[cfg(test)]
mod tests {
    use super::*;

    fn filter(rule: &Value) -> String {
        rule["trigger"]["url-filter"].as_str().unwrap().to_string()
    }

    #[test]
    fn origin_rule_anchors_and_escapes_the_host() {
        let rule = origin_rule("https://ads.example.com").expect("https origin is a rule");
        assert_eq!(
            filter(&rule),
            "^https?://([a-z0-9_-]+\\.)*ads\\.example\\.com[:/]"
        );
        assert_eq!(rule["action"]["type"], "block");
    }

    #[test]
    fn origin_rule_never_wildcards_a_single_label() {
        // Blocking "https://com" must block exactly that host —
        // wildcarding it would match every .com site's subresources.
        let rule = origin_rule("https://com").expect("single-label origin is a rule");
        assert_eq!(filter(&rule), "^https?://com[:/]");
        let ip = origin_rule("https://localhost").expect("localhost is a rule");
        assert_eq!(filter(&ip), "^https?://localhost[:/]");
    }

    #[test]
    fn origin_rule_covers_every_resource_type() {
        // No `resource-type` key at all — that is how WebKit is told
        // "all of them", `document` included.
        let rule = origin_rule("https://example.com").expect("https origin is a rule");
        assert!(rule["trigger"].get("resource-type").is_none());
    }

    #[test]
    fn origin_rule_keeps_an_explicit_port() {
        let rule = origin_rule("http://example.com:8443").expect("port origin is a rule");
        assert_eq!(
            filter(&rule),
            "^https?://([a-z0-9_-]+\\.)*example\\.com:8443/"
        );
    }

    #[test]
    fn origin_rule_drops_a_default_port() {
        let with = origin_rule("https://example.com:443").expect("origin is a rule");
        let without = origin_rule("https://example.com").expect("origin is a rule");
        assert_eq!(filter(&with), filter(&without));
    }

    #[test]
    fn origin_rule_refuses_non_web_schemes() {
        for origin in [
            "file:///etc/passwd",
            "javascript:alert(1)",
            "data:text/html,x",
            "null-event://log",
            "ftp://example.com",
        ] {
            assert!(origin_rule(origin).is_none(), "{origin} should be refused");
        }
    }

    #[test]
    fn origin_rule_refuses_garbage() {
        for origin in ["", "   ", "example.com", "https://", "not a url"] {
            assert!(
                origin_rule(origin).is_none(),
                "{origin:?} should be refused"
            );
        }
    }

    #[test]
    fn user_rules_json_is_none_without_valid_origins() {
        assert!(user_rules_json(&[]).is_none());
        assert!(user_rules_json(&["nonsense".into(), "file:///x".into()]).is_none());
    }

    #[test]
    fn user_rules_json_skips_invalid_entries() {
        let json = user_rules_json(&[
            "https://a.example".into(),
            "nonsense".into(),
            "http://b.example".into(),
        ])
        .expect("two valid origins make a list");
        let parsed: Value = serde_json::from_str(&json).expect("valid json");
        let rules = parsed.as_array().expect("an array");
        assert_eq!(rules.len(), 2);
        assert!(filter(&rules[0]).contains("a\\.example"));
        assert!(filter(&rules[1]).contains("b\\.example"));
    }

    #[test]
    fn bundled_list_is_a_usable_content_blocker() {
        let parsed: Value = serde_json::from_str(ADS_JSON).expect("ads.json is valid json");
        let rules = parsed.as_array().expect("ads.json is an array");
        assert!(!rules.is_empty(), "ads.json is empty");
        // WebKit's own cap on a compiled rule list.
        assert!(rules.len() < 150_000, "ads.json exceeds WebKit's rule cap");
        for rule in rules {
            let filter = rule["trigger"]["url-filter"]
                .as_str()
                .expect("every rule has a url-filter");
            assert!(!filter.is_empty(), "empty url-filter");
            assert!(filter.starts_with("^https?://"), "unanchored: {filter}");
            assert_eq!(rule["action"]["type"], "block");
        }
    }

    #[test]
    fn bundled_list_never_blocks_main_frame_navigations() {
        let parsed: Value = serde_json::from_str(ADS_JSON).expect("ads.json is valid json");
        for rule in parsed.as_array().expect("an array") {
            let types = rule["trigger"]["resource-type"]
                .as_array()
                .expect("the bundled rules name their resource types");
            assert!(
                !types.iter().any(|t| t == "document"),
                "the bundled list must leave navigations to on_navigation"
            );
        }
    }
}
